version: "3.8"
services:
  flask:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
